apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: controlplane
spec:
  version: v1.33.2
  replicas: 1
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: controlplane
    namespace: homelab
  controlPlaneConfig:
    controlplane:
      talosVersion: v1.10.4
      generateType: controlplane
      strategicPatches:
        - |
          - op: add
            path: /machine/install
            value:
              disk: /dev/sda
              extensions:
                - image: ghcr.io/siderolabs/qemu-guest-agent:10.0.2
              extraKernelArgs:
                - net.ifnames=0
          - op: add
            path: /machine/network
            value:
              hostname: controlplane
              nameservers:
                - 8.8.8.8
                - 8.8.4.4
              interfaces:
                - interface: eth0
                  dhcp: false
                  addresses:
                    - 10.0.0.12/24
                  routes:
                    - network: 0.0.0.0/0
                      gateway: 10.0.0.1
          - op: add
            path: /cluster/network
            value:
              cni:
                name: none
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: controlplane
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 4096
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 2
      numSockets: 1
      sourceNode: proxmox
      templateID: 102
      checks:
        skipCloudInitStatus: true