apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: compute-xlarge
spec:
  clusterName: cluster
  replicas: 1
  strategy:
    type: OnDelete
  selector:
    matchLabels:
      node.mmontes.io/name: compute-xlarge
  template:
    metadata:
      labels:
        node.mmontes.io/name: compute-xlarge
    spec:
      clusterName: cluster
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: compute-xlarge
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: compute-xlarge
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: compute-xlarge
spec:
  template:
    spec:
      talosVersion: v1.12 # required by talos bootstrap provider
      generateType: worker
      strategicPatches:
        - |
          - op: add
            path: /machine/install
            value:
              disk: /dev/sda
              image: factory.talos.dev/nocloud-installer/f65b143874f1172a6ae46613f8b223de5fd0fcd59f2fac85e49fd21ea183c097:v1.12.1
              extraKernelArgs:
                - net.ifnames=0
          - op: add
            path: /machine/network
            value:
              hostname: compute-xlarge
              nameservers:
                - 8.8.8.8
                - 8.8.4.4
              interfaces:
                - interface: eth0
                  dhcp: false
                  addresses:
                    - 10.0.0.29/24
                  routes:
                    - network: 0.0.0.0/0
                      gateway: 10.0.0.1
          - op: add
            path: /machine/kubelet
            value:
              image: ghcr.io/siderolabs/kubelet:v1.35.0
              nodeIP:
                validSubnets:
                  - 10.0.0.29/32
              extraConfig:
                registerNode: true
                registerWithTaints:
                  - effect: NoSchedule
                    key: node.mmontes.io/type
                    value: compute-xlarge
              extraArgs:
                rotate-server-certificates: true
          - op: add
            path: /machine/kernel
            value:
              modules:
                - name: btrfs              
                - name: dm-thin-pool
                - name: nvidia
                - name: nvidia_uvm
                - name: nvidia_drm
                - name: nvidia_modeset
          - op: add
            path: /machine/sysctls
            value:
              net.core.bpf_jit_harden: 1       
          - op: add
            path: /machine/nodeLabels
            value:
              node.mmontes.io/type: compute-xlarge
              nvidia.com/gpu.present: true
          - op: add
            path: /cluster/network
            value:
              cni:
                name: none