apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: compute-xlarge
spec:
  clusterName: cluster
  replicas: 1
  strategy:
    type: OnDelete
  selector:
    matchLabels:
      node.mmontes.io/name: compute-xlarge
  template:
    metadata:
      labels:
        node.mmontes.io/name: compute-xlarge
    spec:
      clusterName: cluster
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: compute-xlarge
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: compute-xlarge
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: compute-xlarge
spec:
  template:
    spec:
      talosVersion: v1.14 # required by talos bootstrap provider
      generateType: worker
      strategicPatches:
        - |
          apiVersion: v1alpha1
          kind: UnattendedInstallConfig
          installer:
            image: factory.talos.dev/nocloud-installer/3ed15c02833947ae0444f22e5225c772346e48feb70cb508d0b36c175eddd624:v1.14.2
          provisioning:
            diskSelector:
              match: disk.dev_path == "/dev/sda"
          ---
          apiVersion: v1alpha1
          kind: HostnameConfig
          auto: off
          hostname: compute-xlarge
          ---
          apiVersion: v1alpha1
          kind: LinkConfig
          name: eth0
          addresses:
            - address: 10.0.0.29/24
          routes:
            - gateway: 10.0.0.1
          ---
          apiVersion: v1alpha1
          kind: ResolverConfig
          nameservers:
            - address: 8.8.8.8
            - address: 8.8.4.4
          ---
          apiVersion: v1alpha1
          kind: KubeletConfig
          image: ghcr.io/siderolabs/kubelet:v1.37.0
          config:
            serverTLSBootstrap: true
          ---
          apiVersion: v1alpha1
          kind: KubeNodeConfig
          nodeIP:
            validSubnets:
              - 10.0.0.29/32
          labels:
            node.mmontes.io/type: compute-xlarge
            nvidia.com/gpu.present: "true"
          taints:
            node.mmontes.io/type: compute-xlarge:NoSchedule
          ---
          apiVersion: v1alpha1
          kind: SysctlConfig
          params:
            net.core.bpf_jit_harden: "1"
          ---
          apiVersion: v1alpha1
          kind: KernelModuleConfig
          name: btrfs
          ---
          apiVersion: v1alpha1
          kind: KernelModuleConfig
          name: dm-thin-pool
          ---
          apiVersion: v1alpha1
          kind: KernelModuleConfig
          name: nvidia
          ---
          apiVersion: v1alpha1
          kind: KernelModuleConfig
          name: nvidia_uvm
          ---
          apiVersion: v1alpha1
          kind: KernelModuleConfig
          name: nvidia_drm
          ---
          apiVersion: v1alpha1
          kind: KernelModuleConfig
          name: nvidia_modeset