apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: compute-large
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 12288 # 12Gi
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 8
      numSockets: 1
      sourceNode: proxmox
      templateID: 112
      checks:
        skipCloudInitStatus: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: compute-xlarge
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 49152 # 48Gi
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 16
      numSockets: 1
      sourceNode: proxmox
      templateID: 110
      checks:
        skipCloudInitStatus: true