apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-node-exporter
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: homelab