apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capi-operator
spec:
  chart:
    spec:
      chart: cluster-api-operator
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: capi-operator-system
      version: 0.24.1
  interval: 1h
  values:
    core:
      cluster-api:
        version: v1.12.1
        createNamespace: true
    bootstrap:
      talos:
        version: v0.6.11
        createNamespace: true
    controlPlane:
      talos:
        version: v0.5.12
        createNamespace: true
    infrastructure:
      proxmox:
        version: v0.7.5
        createNamespace: true
    ipam:
      in-cluster:
        version: v1.0.3
        createNamespace: true
    configSecret:
      name: proxmox
      namespace: capi-operator-system
