# See: 
# https://docs.siderolabs.com/talos/v1.14/platform-specific-installations/boot-assets
# https://factory.talos.dev/
# Disk image:
# https://factory.talos.dev/image/8da9288269158668418bcaff7eb8f7d1eb1829090021fbf6dba69b15e79811a8/v1.14.2/nocloud-amd64.raw.xz
# ISO:
# https://factory.talos.dev/image/8da9288269158668418bcaff7eb8f7d1eb1829090021fbf6dba69b15e79811a8/v1.14.2/nocloud-amd64.iso
# Image:
# factory.talos.dev/nocloud-installer/8da9288269158668418bcaff7eb8f7d1eb1829090021fbf6dba69b15e79811a8:v1.14.2
customization:
    extraKernelArgs:
        - net.ifnames=0
    systemExtensions:
        officialExtensions:
            - siderolabs/btrfs
            - siderolabs/iscsi-tools
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/nvidia-open-gpu-kernel-modules-lts
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools