# See: 
# https://docs.siderolabs.com/talos/v1.14/platform-specific-installations/boot-assets
# https://factory.talos.dev/
# Disk image:
# https://factory.talos.dev/image/3ed15c02833947ae0444f22e5225c772346e48feb70cb508d0b36c175eddd624/v1.14.2/nocloud-amd64.raw.xz
# ISO:
# https://factory.talos.dev/image/3ed15c02833947ae0444f22e5225c772346e48feb70cb508d0b36c175eddd624/v1.14.2/nocloud-amd64.iso
# Image:
# factory.talos.dev/nocloud-installer/3ed15c02833947ae0444f22e5225c772346e48feb70cb508d0b36c175eddd624:v1.14.2
customization:
    extraKernelArgs:
        - net.ifnames=0
    systemExtensions:
        officialExtensions:
            - siderolabs/btrfs
            - siderolabs/iscsi-tools
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools