# See: 
# https://docs.siderolabs.com/talos/v1.14/platform-specific-installations/boot-assets
# https://factory.talos.dev/
# Schematic ID: aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8
customization:
    extraKernelArgs:
      - net.ifnames=0
    systemExtensions:
        officialExtensions:
            - siderolabs/btrfs
            - siderolabs/iscsi-tools
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools