apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capi-operator
spec:
  chart:
    spec:
      chart: cluster-api-operator
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: capi-system
      version: 0.20.0
  interval: 1h
  values:
    core:
      cluster-api:
        version: v1.10.2
        namespace: capi-system
    bootstrap:
      talos:
        version: v0.6.9
        namespace: capi-system
    controlPlane:
      talos:
        version: v0.5.10
    infrastructure:
      proxmox:
        version: v0.7.1
        namespace: capi-system
    ipam:
      in-cluster:
        version: v1.0.2
        namespace: capi-system
    configSecret:
      name: proxmox
