apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      version: "v1.18.0"
  interval: 1h
  values:
    crds:
      enabled: false
    prometheus:
      enabled: false
